import { useEffect,useState } from 'react'
import { Link } from 'react-router-dom'
import { getEmployees } from '../api/client'
import type { Employee } from '../api/types'
import { EmptyState,ErrorState,LoadingState } from '../components/States'
import { SectionCard } from '../components/Ui'
export function EmployeeSelector(){const [employees,setEmployees]=useState<Employee[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<unknown>(null),[retryKey,setRetryKey]=useState(0)
 useEffect(()=>{let active=true;getEmployees().then((items)=>{if(active)setEmployees(items)}).catch((reason:unknown)=>{if(active)setError(reason)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[retryKey])
 const retry=()=>{setLoading(true);setError(null);setRetryKey((key)=>key+1)},visible=employees.filter((item)=>`${item.full_name} ${item.role} ${item.department??''}`.toLowerCase().includes(query.toLowerCase()))
 return <div className="page-stack"><div className="hero"><span className="eyebrow">YOUR NEXT CHAPTER STARTS HERE</span><h1>Choose your <span>career path.</span></h1><p>Explore your profile, find your next skill gap, and pick a quest that moves you forward.</p></div><SectionCard title="Select an employee" eyebrow="CAREER PROFILES" action={!loading&&!error&&<span className="count-pill">{employees.length} available</span>}>{loading?<LoadingState label="Loading employees..."/>:error?<ErrorState error={error} onRetry={retry}/>:employees.length===0?<EmptyState title="No employees yet" message="The API returned an empty employee list."/>:<><label className="search-label" htmlFor="employee-search">Search employees</label><input id="employee-search" className="search-input" value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Name, role, or department"/>{visible.length===0?<EmptyState title="No matches" message="Try a different search term."/>:<div className="employee-grid">{visible.map((item)=><Link className="employee-card" to={`/employee/${encodeURIComponent(item.employee_id)}`} key={item.employee_id}><span className="avatar">{item.full_name.split(' ').map((part)=>part[0]).slice(0,2).join('')}</span><span className="employee-card-body"><strong>{item.full_name}</strong><span>{item.role}</span><small>{item.department??'Department unavailable'} · {item.grade}</small></span><span className="card-arrow">↗</span></Link>)}</div>}</>}</SectionCard></div>}
